#NAME: Ryan Riahi
#EMAIL: ryanr08@gmail.com
#ID: 105138860

lab0: lab1a.c 
	gcc -g lab1a.c -o lab1a -Wextra -Wall
clean:
	rm -rf lab1a  lab1a-105138860.tar.gz

dist: lab0
	tar -zcf lab1a-105138860.tar.gz lab1a.c Makefile README 
