#NAME: Anurag Sandireddy, Ryan Riahi
#EMAIL: anurag.sandireddy@gmail.com, ryanr08@gmail.com
#ID: 805114200, 105138860

default:
	-rm -f lab3b
	ln lab3b.py lab3b
dist:
	tar -czvf lab3b-805114200.tar.gz Makefile README lab3b.py
clean:
	-rm lab3b-805114200.tar.gz
	-rm lab3b