#NAME: Anurag Sandireddy, Ryan Riahi EMAIL: anurag.sandireddy@gmail.com, ryanr08@gmail.com
#ID: 805114200, 105138860
default:
	gcc -Wall -Wextra -g lab3a.c -o lab3a -lm
dist: default
	tar -czvf lab3a-805114200.tar.gz Makefile README lab3a.c ext2_fs.h 
clean:
	-rm -f *.tar.gz
	-rm -f *.csv
	-rm -f lab3a