#NAME: Ryan Riahi
#EMAIL: ryanr08@gmail.com
#ID: 105138860

default: README build_run.png connected.png copy.png git.png my_beaglebone.jpg Makefile
	tar -czvf lab4a-105138860.tar.gz README build_run.png connected.png copy.png git.png my_beaglebone.jpg Makefile